--
-- The MTS ice EJB project is the base framework for the CDS Framework Middle Tier Service.
--
-- Copyright (C) 2016 New York City Department of Health and Mental Hygiene, Bureau of Immunization
-- Contributions by HLN Consulting, LLC
--
-- This program is free software: you can redistribute it and/or modify it under the terms of the GNU
-- Lesser General Public License as published by the Free Software Foundation, either version 3 of the
-- License, or (at your option) any later version. You should have received a copy of the GNU Lesser
-- General Public License along with this program. If not, see <http://www.gnu.org/licenses/> for more
-- details.
--
-- The above-named contributors (HLN Consulting, LLC) are also licensed by the New York City
-- Department of Health and Mental Hygiene, Bureau of Immunization to have (without restriction,
-- limitation, and warranty) complete irrevocable access and rights to this project.
--
-- This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; THE
--
-- SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING,
-- BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
-- NONINFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS, IF ANY, OR DEVELOPERS BE LIABLE FOR
-- ANY CLAIM, DAMAGES, OR OTHER LIABILITY OF ANY KIND, ARISING FROM, OUT OF, OR IN CONNECTION WITH
-- THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
--
-- For more information about this software, see https://www.hln.com/services/open-source/ or send
-- correspondence to ice@hln.com.
--

-- // ice_vaccine
-- Migration SQL that makes the change goes here.

CREATE TABLE ice_vaccine (
            vaccine_id VARCHAR(32) PRIMARY KEY,
            vaccine_code_id VARCHAR(32) not null,
            vaccine_name varchar(128) not null,
            primary_concept VARCHAR(32),
            licensed_min_age_for_use varchar(32),
            licensed_max_age_for_use varchar(32),
            manufacturer_code_id varchar(32),
            trade_name varchar(128),
            valid_min_age_for_use varchar(32),
            valid_max_age_for_use varchar(32),
            active char(1) default 'Y' not null,
            min_date_for_use date,
            max_date_for_use date,
            LAST_MOD_ID VARCHAR(32) NOT NULL,
            LAST_MOD_DATETIME timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CREATE_ID VARCHAR(32) NOT NULL,
            CREATE_DATETIME timestamp NOT NULL);

alter table ice_vaccine add constraint fk_ivvid2cccid foreign key (vaccine_code_id) references cds_code (code_id);

INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('1063d02b120f84c7d2e30b098404284d', '1063d02b120f84c7d2e30b098404284d', 'HPV, bivalent (CERVARIX)', 'a025f7e22ad9d7bc5df8438b67f66712', NULL, NULL, NULL, 'CERVARIX', NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('10ad21c2ca078ac4293e56dc5c7fb4a7', 'd8d690813be570868cbfe9cdd63d9187', 'DTP-Hib-Hep B', '19fdf3518aea0b4d3c198509b4746295', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('115011c96e54f5e1cc044f76f69e77b2', '115011c96e54f5e1cc044f76f69e77b2', 'rotavirus, monovalent (ROTARIX)', 'c9244d3cd3167420cc720b68749f18e6', NULL, NULL, NULL, 'ROTARIX', NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('12eda6eda040afed588639de6250700c', '52ba1d7a1ccfe5be84f6d1a9b5e608a3', 'influenza nasal, unspecified formulation', '1b3a153dc564038b802335238fc6e2bf', NULL, NULL, NULL, NULL, '2y - 4d', NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('16b7163c2814a310a9d392c23d76e143', '16b7163c2814a310a9d392c23d76e143', 'mumps', 'c299b5a35cc0c15c33b8d79d867f066b', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('19a8fab71b99131a16ebf3e42e5f9fc7', '7e7eeda75d1ea89921cab7d86b66c447', 'Hep B, dialysis', '3043187179ad37048a30a2dbbd6f1ad4', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('1a211cb73bc3b484d1e0852b18500a1e', '1a211cb73bc3b484d1e0852b18500a1e', 'DTaP, 5 pertussis antigens (DAPTACEL)', NULL, NULL, NULL, NULL, 'DAPTACEL', NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('1a72a3652ad621ef6c142028bc827e1b', '1a72a3652ad621ef6c142028bc827e1b', 'measles', '184d96ab9450466838e36975af8d5893', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('1b3b5e305c967a32e20a9a447bad47e5', '1b3b5e305c967a32e20a9a447bad47e5', 'H1N1-09 NOS', '7b471a502ec26419b439b90ff26f756a', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('1d6f24415002fc1ed3f31282eb3db7bb', '1d6f24415002fc1ed3f31282eb3db7bb', 'HPV NOS', '4de9953e65c12555d0d944e9ef544a25', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('260375739a4e64aa48a56f23a6d64cdf', 'd1fff1abfe5eab959f304de38f10d43c', 'meningococcal MCV4 NOS', NULL, NULL, NULL, NULL, NULL, '9m - 4d', NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('26b5eadb78914bfa390dc8b1d7d7a37c', '26b5eadb78914bfa390dc8b1d7d7a37c', 'IPV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('2880c23dd8ad8d9b3bba5028af2c4e4e', '43041e87d8e921484eee385ac621cf9a', 'influenza, intradermal, preservative-free', 'db3d31988458af71e7b83fa2dba19064', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('2a724fd66373612cfcaa92f7341e246e', '2fb18cfe6dc2701f7260e660ed0ee5c3', 'polio NOS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('2e386bad52cbbb36c4dd91e3129c8922', '53f358d0b6e07c53d9a118c39a4182db', 'Hep B, adult', 'a0394184f5f772394491eba2fdd2cd6d', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('31afa04db3aa44e0e61e76c626a3be4e', '363f183aa6055d052fd7900e338cf559', 'meningococcal MPSV4 (MENOMUNE)', NULL, NULL, NULL, 'f03d3788311fccd25ab0ca66266f9cf2', 'MENOMUNE', '2y - 4d', NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('33a5b231185ea648ac237f1989da814a', '9f4c6120a5c2be073a0519cb6f9b9d2f', 'Hep A, pediatric, NOS', 'ca726c47e1a6aecc572877b2cdbe2d8b', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('3449a3ec9b382a55bcdc6dcb4f5110f5', '3fff865fe68daee74d69c5e0c7750d0e', 'influenza, live, intranasal, quadrivalent', '1889289e19733e8ba0ff193663bac407', NULL, NULL, NULL, NULL, '2y - 4d', NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('35282fcad02f488f22f57a746c944421', '72992266a4c25a5e6e5f132a9ede2680', 'Hep A, adult', 'efa957475fbd88fe9b2ef107a57e27fa', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('37e5fa116314b6dc5b698c08afea530c', 'f43885acb83bafd76ebec01b6f53f6cf', 'influenza NOS', '7469b4142956af6f9ae273ec7f564096', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('39b53d6016e88f5784bad89ecd3fde2e', 'e3da750a24577410a9794edcb2f406b6', 'DTP-Hib (TETRAMUNE)', 'bf5265afc7dba531b351010e3617af3c', NULL, NULL, NULL, 'TETRAMUNE', NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('43c1aefb6b54e4f04bb00c87b206195e', '43c1aefb6b54e4f04bb00c87b206195e', 'OPV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('4498350f8bdd4e60b0314fcb3c22e827', '37faef5213ff09e3ef4906c32ef40e0b', 'DT, pediatric', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('46eb9a9d4a483694c03341125900c46b', 'a9527a3639c6a6c5a04d2728b7fc42c0', 'HPV, quadrivalent (GARDASIL)', '6fdcddfe9d36d73e2e6664dc873e9815', NULL, NULL, NULL, 'GARDASIL', NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('47fe49b03811a40755c47cd4b74ccdfa', '47fe49b03811a40755c47cd4b74ccdfa', 'Td, adult, absorbed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('50a0e2cd1feca24fab3422cda3367c26', '6334689712dcc4ebf302c90968682853', 'Hib (PRP-OMP) (PEDVAXHIB)', '58ddc48d2d7a8a57a71275111863b20b', NULL, NULL, NULL, 'PEDVAXHIB', NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('50ff9267f5a8a21ef2086062d6e24343', '89d9d0aa5f1e35db59a2734281bf3a63', 'Hep B NOS', '19d03d8091aa3f4da6d21e27d0843660', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('5178e23c337a26a1ce17a4a73f8bf97b', '5178e23c337a26a1ce17a4a73f8bf97b', 'Hib (PRP-T) (ACTHIB; HIBERIX; OMNIHIB)', 'c470f1b18d7e423673daa5c51e528cce', NULL, NULL, NULL, 'ACTHIB; HIBERIX; OMNIHIB', NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('5346f65f8d180de8781cdaaa5ffaff33', '5346f65f8d180de8781cdaaa5ffaff33', 'influenza, live, intranasal', '39c89978fd27b14a2403e2fe3673fc64', NULL, NULL, NULL, NULL, '2y - 4d', NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('59e02e084e71ebc4cf13c0a748e4f47a', '59e02e084e71ebc4cf13c0a748e4f47a', 'Hib NOS', '6c7bebb4409d458b185c729bde62b711', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('5b04394f57e2cd25a8f995ff5d4d0854', '5b04394f57e2cd25a8f995ff5d4d0854', 'varicella', '5511651bd1110b4df4fbd90445667214', NULL, NULL, '21e1fa8e8288d90ef82ba31ad0ec2533', NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('5bd4d31540e5a654ac10aafd9221ac61', 'bd1b49f5a89652d6db5c587594136f42', 'influenza, recombinant, inj., preservative-free', '1e59777d1dd3e3c4ea8c82e98639aed9', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('5c921f606de397f71d2501771c38c192', 'f8ef6fc7a9f39e0f6e8a56aeda960db3', 'Hep A, ped/adol, 2-dose', 'e23434e456e04fc97c5f73d883e09e86', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('6699c4d58521edb9c091072e976bc67d', '6699c4d58521edb9c091072e976bc67d', 'meningococcal MCV4P (MENACTRA)', NULL, NULL, NULL, NULL, 'MENACTRA', '9m - 4d', NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('6883576bd868da1d907142ade9f7b923', 'bee2f502a3d076e64a219e335957803f', 'Hib-Hep B (COMVAX)', '10fb5b1f93f7eba82ee23c2aec5561d9', NULL, NULL, NULL, 'COMVAX', NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('696564f7f1fc0533d4f5dd85ed05cfea', '696564f7f1fc0533d4f5dd85ed05cfea', 'influenza, split ', 'c10a2862e338ccecab4c9567d26c3192', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('6a93b7b5eb793339480570defbe7fe14', '6a93b7b5eb793339480570defbe7fe14', 'influenza, injectable', '6a1ae4b797d662b5b93ae1772a1e2b22', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('6c7949af1810cd1183895825be4b8ce1', '6c7949af1810cd1183895825be4b8ce1', 'H1N1-09, preservative-free', 'a2ac7864a367aebef380e4af98dbd10e', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('6ccad31d85f1a1bf991e46c3dc1e0e09', '6b1fd318ceda97a08812b2a71ba80a67', 'Hib (PRP-D) (PROHIBIT)', '5c4debcc6268bea71cc5d8ce5a79d399', NULL, NULL, NULL, 'PROHIBIT', NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('6d3e2c6f7b0de8a9785bea8df68f0c47', '6d3e2c6f7b0de8a9785bea8df68f0c47', 'Rotavirus NOS', '138fd34a38afddffffccc5e0b23d048b', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('6e89da7570445099ccaca472a4510dbd', '6e89da7570445099ccaca472a4510dbd', 'rotavirus, pentavalent (ROTATEQ)', '102a2e4fd09b28228a9e44a24fe12dc3', NULL, NULL, NULL, 'ROTATEQ', NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('6ed89869ac0ace491bec4526dec327f8', '6ed89869ac0ace491bec4526dec327f8', 'DTP', '276423739f3aa1f032f193b0e8071be3', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('6fc9d6c656da7c741947e8bc321b721a', '699e36db6ca1ea07c9c4c2ee86053f96', 'Influenza, injectable, MDCK, (ccIIV3), trivalent, preservative free', 'd7840c1215b97a29d9e0dfaa727f6fde', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('72f4c00c91390f7a5df4a0d6fc492894', '72f4c00c91390f7a5df4a0d6fc492894', 'influenza, whole', '35c28d47509f9e405ab749f9e032e2af', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('73e1989170ca5c43a4767dfbf11f9c6a', 'a0e226a6a44b1eafb30b6cb4ccef45c6', 'rubella/mumps', '4ed70dfd50f032187d63bdbd6b6bfced', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('7a2b1bee78f886391cbd446123d9b20d', '6d5c6d027b55ff047b5e12e16d634f8e', 'DTaP-Hib (TRIHIBIT)', '7a46c784275cefba9f603a377598ea24', NULL, NULL, NULL, 'TRIHIBIT', NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('7b0195669cf49dbbacac7d82f3c70042', '7b0195669cf49dbbacac7d82f3c70042', 'rubella', '504eed2afd40f3c8f6e9d805a59f3226', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('7d3d80b067c1fa9390eb3b50f20075d9', '7d3d80b067c1fa9390eb3b50f20075d9', 'pneumococcal conjugate PCV 7 (PREVNAR 7)', 'dd734acceb82d02eda3dddaf5f5722df', NULL, NULL, NULL, 'PREVNAR 7', NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('7e1471be78ff8ead9772f37fd6aac6cf', '7e1471be78ff8ead9772f37fd6aac6cf', 'H1N1-09, nasal', 'ff166a5f3b060f15b138afd5d87cd198', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('807930df85c91a3ebe707f09b9c8c609', '807930df85c91a3ebe707f09b9c8c609', 'influenza, high dose ', '6d5c5e09607d1f1072ceb0962f94f046', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('8193b4c4e4552b432a72232fe733d32a', 'a2cfcee1cefe42eab42e2318645d9f33', 'meningococcal C conjugate', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('886903982dada4949ab8488698671819', '886903982dada4949ab8488698671819', 'DTaP-Hep B-IPV (PEDIARIX)', 'e2d298da31b2d03859f7898c42efcd21', NULL, NULL, NULL, 'PEDIARIX', NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('8d94a63bed4e53e27c403fb72d68f884', '9bb88b1daa2dafd48c265a9e3a7bc878', 'Influenza, injectable, quadrivalent (IIV4), preservative free', '10e4d96a58df7d7f743a90ad36541ac9', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('8e3f621a6368e6d294211b84b09da1b8', '8e3f621a6368e6d294211b84b09da1b8', 'Td, adult, preservative free', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('90416702fd324f51efb285505a8cafa6', 'b6f1d7bd6d6e5fc6db728c48678967c5', 'Influenza-IIV4, ID Presrv-free(18-64yrs)', '8e251c50bd38bb981132b959abb9daf3', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('940719422398be2efc9ae08751bf417b', '940719422398be2efc9ae08751bf417b', 'pneumococcal conjugate PCV 13', 'b0fd342b9f5b6e47e4a3cc41b03b10d8', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('9430c9781e2189b05c3cd6329af76fc6', 'cc422a1c3027b283a6caa0c7ef17e551', 'Meningococcal C & Y', '7aa441fab874ac4de8e10449a6be361d', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('99acdd2bcedffac9e0205217da0357fa', '99acdd2bcedffac9e0205217da0357fa', 'pertussis', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('9c47e492cb267923614e4827fa3d6d2b', '9c47e492cb267923614e4827fa3d6d2b', 'influenza, injectable, preservative-free', 'a7107045db775d88f6424726c017fb67', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('9d8e6e80e7805d2de2594a5f11fd7fc7', '9d8e6e80e7805d2de2594a5f11fd7fc7', 'pneumococcal NOS', 'd3b8cb4755e5368e7c2cfe1714a87523', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('a4900f2c8af205febdade2da44b7aa71', '39d17b6e86a657837bb1b2dfe11bfdb6', 'Hib (HbOC) (HIBTITER)', '677737d6c0c21c9cd8d6f927b7abd8e9', NULL, NULL, NULL, 'HIBTITER', NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('a58a28918894428bdefab782a7f1c215', 'a58a28918894428bdefab782a7f1c215', 'Hep B, adolescent or pediatric', 'dab138bb7a47efb1fffca51b0ae3965d', NULL, NULL, NULL, NULL, NULL, '20y', 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('acf262fa464441cd22704f6f70839150', 'acf262fa464441cd22704f6f70839150', 'Hep A, ped/adol, 3-dose', '46c3979a44a0577094bb66b348820427', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('af01738887787f03355fe627864bdaaf', 'a94856e326cc369c5a5ebb1e53fd76e5', 'Td, adult NOS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('b041a921609bd35ceb980ef6fa484baf', '10320d22a2631f2c5a07ee7734b80528', 'MMR-Varicella', 'b0b54156779438ccee7deb6fc2a169ee', NULL, '13y - 1d', NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('b6ffa4b8bc0847078f9be7209b5df876', 'b6ffa4b8bc0847078f9be7209b5df876', 'DTaP-IPV (KINRIX)', NULL, NULL, NULL, NULL, 'KINRIX', NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('b8a06f21141c029b2833275a8f036ca3', '7fee2edcf1b3e44a94a16059bef44072', 'meningococcal C/Y-HIB PRP (MENHIBRIX)', '11290f644fbf2a79d3ef3336bbfeb63e', NULL, NULL, NULL, 'MENHIBRIX', NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('bb59ba73a1072418faaa463ee5f472dc', 'bb59ba73a1072418faaa463ee5f472dc', 'DTaP', 'a80d7ce2e56e4ed1a21531658da7063d', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('be777d762c0f14a4bf003e0a8a9d0fc6', 'be777d762c0f14a4bf003e0a8a9d0fc6', 'DTaP-Hib-IPV (PENTACEL)', 'acd1ae4fb14d3b2d6ac36e15f8cacbb7', NULL, NULL, NULL, 'PENTACEL', NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('c955ffa4dc71edfe7b4f831ac3729c7d', 'c955ffa4dc71edfe7b4f831ac3729c7d', 'H1N1-09, injectable', '50c4a3779817b6aaedc7e1442d9c73f2', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('cd4336f615b9ce6d8aa55209dd4b0b55', '6d78bb9f5eff5cbfa9d0b2343ba91360', 'Influenza-IIV4, IM (>3yrs)', '2bf18017335250b555a8c3c6875f35b3', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('ce46656efb01eeb469434730796ac0aa', '36fea054a6b78d2a10139b43480b1083', 'pneumococcal polysaccharide  (PNEUMOVAX 23)', 'dc0a46d2b7763a6b34c1a6764d4b2950', NULL, NULL, NULL, 'PNEUMOVAX 23', '2y - 4d', NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('d5ad3fae35b79aac029551e26912a799', '993ea3ebe57ee235d2affb1173e40388', 'Influenza-IIV4,IM Presrv-free (6-35mos)', '1386388188a237e3c79939cfe9ba8006', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('dbb90d607a346452e82c6a526f6dd727', 'dbb90d607a346452e82c6a526f6dd727', 'Tdap', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('dcb01536cd425956165af9d374c2baa8', 'dcb01536cd425956165af9d374c2baa8', 'meningococcal MCV4O (MENVEO )', NULL, NULL, NULL, NULL, 'MENVEO ', '2m - 4d', NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('dedba4495cfa131c96b4dc0b43138d83', '68a94ed7b016986a40f6551b3f7a9cbf', 'Hep A NOS', '40b8efb0eb48b5d2bdeb47979512b64a', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('e3f3ab4bb0643e385b69f33b34c01cf8', 'e3f3ab4bb0643e385b69f33b34c01cf8', 'Hep A-Hep B (TWINRIX)', 'e2b4ceac589c3fb1b28b722ce5571685', NULL, NULL, NULL, 'TWINRIX', NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('e5d15051f018680a81ba7a0bb2f2e0dc', 'e5d15051f018680a81ba7a0bb2f2e0dc', 'meningococcal NOS', NULL, NULL, NULL, NULL, NULL, '9m - 4d', NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('e84fd85087efe8e35b9c3adabd0b4e4b', 'fb284f06c8a73851707a9610789c8381', 'rotavirus, tetravalent', '2de4f72f1078230a474e31ff4e51ef35', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('ed444e8a59047e86b28e89e335b21bfb', 'ed444e8a59047e86b28e89e335b21bfb', 'MMR', '1debbebcd1c494a8213ab05dd71f6d62', NULL, NULL, '21e1fa8e8288d90ef82ba31ad0ec2533', NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('ed635e962167812224f6a70a6c7705b6', '71a48f0d94463afe5ff7a3aed4e3ee2e', 'Hep B, adolescent/high risk infant', 'afe13f163e3eda0853767f00c02aaafa', NULL, NULL, NULL, NULL, NULL, '20y', 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('f2e213c64816a94de7c4fbb58ffb6b70', '84082e62128fabcd5a5364f78de9b631', 'pneumococcal conjugate NOS ', '5dbf4c241ea421019081812746c9126a', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('f45e4262faf28b856a6c2d55fccf62b6', 'd355695d931880b31ff86595b44f8985', 'HPV (HPV9-Gardasil 9)', 'bfc390292f863e801c9854ca248e2c0c', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('f715a2ea209729e852117d0a305799e1', 'f715a2ea209729e852117d0a305799e1', 'measles/rubella', '13e71f70ad9630fcae7688fb37fa1389', NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('f9e3be777817ba68958c4fa7a3d89b90', 'f9e3be777817ba68958c4fa7a3d89b90', 'DTaP NOS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO ice_vaccine (vaccine_id, vaccine_code_id, vaccine_name, primary_concept, licensed_min_age_for_use, licensed_max_age_for_use, manufacturer_code_id, trade_name, valid_min_age_for_use, valid_max_age_for_use, active, min_date_for_use, max_date_for_use, last_mod_id, last_mod_datetime, create_id, create_datetime) 
    VALUES ('fe19b4a3be03ac3c524cf690ce4e03f5', '2363716213b0f3a8e85243c976f3e7df', 'Td, not adsorbed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);

-- //@UNDO
-- SQL to undo the change goes here.

drop table ice_vaccine;
